//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetsisSQLWebApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using System.Collections.Generic;
    using NetsisSQLWebApi.Controllers;

    public partial class NetsisEntities : DbContext
    {
        public NetsisEntities()
            : base("name=NetsisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<STOK_RAPOR_Result> STOK_RAPOR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STOK_RAPOR_Result>("STOK_RAPOR");
        }
    
        public virtual ObjectResult<AYK_KIMLIK_Result> AYK_KIMLIK()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AYK_KIMLIK_Result>("AYK_KIMLIK");
        }
    
        public virtual ObjectResult<STOK_AL_Result> STOK_AL(string sT_KOD)
        {
            var sT_KODParameter = sT_KOD != null ?
                new ObjectParameter("ST_KOD", sT_KOD) :
                new ObjectParameter("ST_KOD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STOK_AL_Result>("STOK_AL", sT_KODParameter);
        }
    
        public virtual ObjectResult<STOK_AL_CINS_Result> STOK_AL_CINS(string cINS)
        {
            var cINSParameter = cINS != null ?
                new ObjectParameter("CINS", cINS) :
                new ObjectParameter("CINS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STOK_AL_CINS_Result>("STOK_AL_CINS", cINSParameter);
        }
    
        public virtual ObjectResult<STOK_DUS_Result> STOK_DUS(string sT_KOD, Nullable<decimal> aDET)
        {
            var sT_KODParameter = sT_KOD != null ?
                new ObjectParameter("ST_KOD", sT_KOD) :
                new ObjectParameter("ST_KOD", typeof(string));
    
            var aDETParameter = aDET.HasValue ?
                new ObjectParameter("ADET", aDET) :
                new ObjectParameter("ADET", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STOK_DUS_Result>("STOK_DUS", sT_KODParameter, aDETParameter);
        }
    
        public virtual ObjectResult<CARI_EKLE_Result> CARI_EKLE(string cARI_KOD, string cARI_TEL, string cARI_IL, string cARI_ISIM, string cARI_ADRES, string cARI_ILCE, string eMAIL, string tCNO, string kAYITYAPANKUL, string kAYITTARIHI)
        {
            var cARI_KODParameter = cARI_KOD != null ?
                new ObjectParameter("CARI_KOD", cARI_KOD) :
                new ObjectParameter("CARI_KOD", typeof(string));
    
            var cARI_TELParameter = cARI_TEL != null ?
                new ObjectParameter("CARI_TEL", cARI_TEL) :
                new ObjectParameter("CARI_TEL", typeof(string));
    
            var cARI_ILParameter = cARI_IL != null ?
                new ObjectParameter("CARI_IL", cARI_IL) :
                new ObjectParameter("CARI_IL", typeof(string));
    
            var cARI_ISIMParameter = cARI_ISIM != null ?
                new ObjectParameter("CARI_ISIM", cARI_ISIM) :
                new ObjectParameter("CARI_ISIM", typeof(string));
    
            var cARI_ADRESParameter = cARI_ADRES != null ?
                new ObjectParameter("CARI_ADRES", cARI_ADRES) :
                new ObjectParameter("CARI_ADRES", typeof(string));
    
            var cARI_ILCEParameter = cARI_ILCE != null ?
                new ObjectParameter("CARI_ILCE", cARI_ILCE) :
                new ObjectParameter("CARI_ILCE", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var tCNOParameter = tCNO != null ?
                new ObjectParameter("TCNO", tCNO) :
                new ObjectParameter("TCNO", typeof(string));
    
            var kAYITYAPANKULParameter = kAYITYAPANKUL != null ?
                new ObjectParameter("KAYITYAPANKUL", kAYITYAPANKUL) :
                new ObjectParameter("KAYITYAPANKUL", typeof(string));
    
            var kAYITTARIHIParameter = kAYITTARIHI != null ?
                new ObjectParameter("KAYITTARIHI", kAYITTARIHI) :
                new ObjectParameter("KAYITTARIHI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CARI_EKLE_Result>("CARI_EKLE", cARI_KODParameter, cARI_TELParameter, cARI_ILParameter, cARI_ISIMParameter, cARI_ADRESParameter, cARI_ILCEParameter, eMAILParameter, tCNOParameter, kAYITYAPANKULParameter, kAYITTARIHIParameter);
        }

    }
}
